# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e1cf63948cc20d55518a919e85c53ee62a426259b6ecd7523547f473094da67bd9efd46ca663230a629f76accef558e17e6306c5cf83ae7ee9289d2de3fbcd3

test:
  secret_key_base: 3b6dc5a479e97ae98da8442202136157f256967f83a982299d5e3bd97eecca3cae2374bdd58aed024ae6fc4ec37ced5332ab510c1bb0ec28958de1cc9bd49a69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
